version: "3.9"
services:
  postgres1:
    container_name: postgres1
    image: postgres:16
    environment:
      POSTGRES_DB: "proteichatdb"
      POSTGRES_USER: "proteiuser"
      POSTGRES_PASSWORD: "1234"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../Init Database:/docker-entrypoint-initdb.d
      - proteichatdb-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - postgres
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:7.3
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@protei.com
      PGADMIN_DEFAULT_PASSWORD: "1234"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - postgres
  chat-backend:
    container_name: chat-backend
    build: .
    ports:
      - "8080:8080"
    networks:
      - postgres
    depends_on:
      - postgres1
    restart: on-failure
volumes:
  proteichatdb-data:
  pgadmin-data:
networks:
  postgres:
    driver: bridge