version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: "proteichatdb"
      POSTGRES_USER: "proteiuser"
      POSTGRES_PASSWORD: "1234"
    ports:
      - "54333:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: "1234"
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  pgadmin-data: